name = "askthebio-agent"
main = "src/index.ts"
compatibility_date = "2025-10-26"

[[r2_buckets]]
binding = "R2"
bucket_name = "askthebio-data"

[vars]
GEMINI_MODEL = "gemini-2.5-flash-lite"
PERSON_NAME = "Diego Giorgini"
CONTEXT_KEY = "diego-giorgini-y4tfirbg/latest/extraction.md"
CONTEXT_SNIPPET_LENGTH = 500000
MAX_OUTPUT_TOKENS = 8192

[[ratelimits]]
# N requests every M seconds
name = "IP_LIMITER_BURST"
namespace_id = "1001"
simple = { limit = 10, period = 10 }

[[ratelimits]]
name = "IP_LIMITER_MINUTE"
namespace_id = "1002"
simple = { limit = 20, period = 60 }
